```{r}

library(data.table)
library(ggplot2)

d <- fread("res.csv", sep=":")
names(d) <- c("size","tool","ncores","cores","tcores","runtime","auc")

d[, pcores:=sub(" $","",paste(ncores,tcores))]

pcores_order <- unique(d$pcores)
d[, pcores:=factor(pcores, levels=pcores_order)]

d <- d[tool=="h2o"]

```

```{r}

ggplot(d) + geom_boxplot(aes(x = pcores, y = runtime, color = tool)) +
  coord_flip() + facet_wrap(~size, scales = "free", ncol = 2) + ylim(c(0,NA))

dd <- d[!grepl(",",cores) & tcores==""]

ggplot(dd) + geom_boxplot(aes(x = pcores, y = runtime, color = tool)) +
  coord_flip() + facet_wrap(~size, scales = "free", ncol = 2) + ylim(c(0,NA))

dd2 <- d[, .(runtime=mean(runtime)), by=.(size,ncores)]
dd2[, runtime_prev := shift(runtime, 1L, type="lag")]
dd2[ncores>1, speedup_vs_half_that_many_cores:=runtime_prev/runtime]
dd2

ggplot(dd2[ncores<=16 & ncores>1], aes(x = as.factor(ncores), y = speedup_vs_half_that_many_cores,
            color = as.factor(size), group= as.factor(size), ymin=0)) +
  geom_point(size=3) + geom_line() + geom_hline(yintercept = 2, color = "red", size = 1.5) 

```

