```{r}

library(data.table)
library(ggplot2)

d <- fread("res.csv", sep=":")
names(d) <- c("size","tool","ncores","cores","tcores","runtime","auc")

d[, pcores:=sub(" $","",paste(ncores,tcores))]
#pcores_order <- unique(d$pcores)
pcores_order <- c("4","8","12","16","24","36","48","48 HT","96 ALL")
d[, pcores:=factor(pcores, levels=pcores_order)]

d[, tool:=factor(tool, levels = c("h2o","xgboost","lightgbm","catboost"))]

```

```{r fig.height=9, fig.width=11}

ggplot(d) + geom_boxplot(aes(x = pcores, y = runtime, color = tool)) +
  coord_flip() + facet_wrap(~tool+size, scales = "free", ncol = 3) + ylim(c(0,NA))

# ggplot(d[ncores>=4]) + geom_boxplot(aes(x = pcores, y = runtime, color = tool)) +
#   coord_flip() + facet_wrap(~tool+size, scales = "free", ncol = 3) + ylim(c(0,NA))

```

```{r fig.height=10, fig.width=11}

dd <- d[ncores<=48 & !grepl(",",cores)]

ggplot(dd) + geom_boxplot(aes(x = pcores, y = runtime, color = tool)) +
  coord_flip() + facet_wrap(~tool+size, scales = "free", ncol = 3) + ylim(c(0,NA))

dd_4c <- dd[ncores==4,.(runtime_4c=mean(runtime)),by=.(tool,size)]
dd <- merge(dd, dd_4c,all.x = TRUE, allow.cartesian = TRUE)

dd[, speedup := (1/runtime)/(1/runtime_4c), by=.(tool,size)]
options(digits=2)
xtabs(speedup~size+tool, dd[ncores==8, .(speedup=mean(speedup)), by=.(tool, size)])
xtabs(speedup~size+tool, dd[ncores==24, .(speedup=mean(speedup)), by=.(tool, size)])
xtabs(speedup~size+tool, dd[ncores==48, .(speedup=mean(speedup)), by=.(tool, size)])

ggplot(dd) + geom_boxplot(aes(x = as.factor(ncores), y = speedup, color = tool)) +
  facet_grid(tool~size, scales = "free") + ylim(c(0,NA))


dd_48c <- d[cores=="0-47",.(runtime_48c=mean(runtime)),by=.(tool,size)]
dd_96c <- d[cores=="0-95",.(runtime_96c=mean(runtime)),by=.(tool,size)]
dd_ht <- merge(dd_48c, dd_96c)
dd_ht[,ht_pc:=((1/runtime_96c)/(1/runtime_48c)-1)*100]
options(digits=1)
xtabs(ht_pc~size+tool, dd_ht)

```

```{r fig.height=3.5, fig.width=6}

ggplot(dd_ht, aes(x = size, y = ht_pc, color = tool, ymin=-100)) + geom_point() + geom_line() + scale_x_log10() + geom_hline(yintercept = 0, color = "red", size = 1.5) + scale_y_continuous(breaks = seq(-100,100,by=20))

ggplot(d, aes(x = size, y = auc, color = tool)) + geom_point() + geom_line() + scale_x_log10()

```

```{r fig.height=6, fig.width=9}

ggplot(dd) + geom_boxplot(aes(x = pcores, y = runtime/size, color = as.factor(size))) + facet_wrap(~tool, scales = "free", ncol=2) + ylim(c(0,NA))

ggplot(d[tool=="xgboost" & size==1]) + geom_boxplot(aes(x = pcores, y = runtime), color = "blue") +
  coord_flip() + facet_wrap(~tool+size, scales = "free") + ylim(c(0,NA)) +
  theme_grey(base_size = 22)

ggplot(d[tool=="lightgbm" & size==1]) + geom_boxplot(aes(x = pcores, y = runtime), color = "red") +
  coord_flip() + facet_wrap(~tool+size, scales = "free") + ylim(c(0,NA)) +
  theme_grey(base_size = 22)


```

