```{r}

library(data.table)
library(ggplot2)

d <- fread("res.csv")
names(d) <- c("size","tool","ncores","cores","tcores","runtime","auc")

d[, pcores:=sub(" $","",paste(ncores,tcores))]

pcores_order <- unique(d$pcores)
d[, pcores:=factor(pcores, levels=pcores_order)]

```

```{r fig.height=8, fig.width=12}

ggplot(d) + geom_boxplot(aes(x = pcores, y = runtime, color = tool)) +
  coord_flip() + facet_wrap(~tool+size, scales = "free") + ylim(c(0,NA))

ggplot(d[ncores<=16]) + geom_boxplot(aes(x = pcores, y = runtime, color = tool)) +
  coord_flip() + facet_wrap(~tool+size, scales = "free") + ylim(c(0,NA))

ggplot(d[ncores>=16]) + geom_boxplot(aes(x = pcores, y = runtime, color = tool)) +
  coord_flip() + facet_wrap(~tool+size, scales = "free") + ylim(c(0,NA))

ggplot(d[ncores>=16 & !(tool=="lightgbm" & ncores>=62)]) + 
  geom_boxplot(aes(x = pcores, y = runtime, color = tool)) +
  coord_flip() + facet_wrap(~tool+size, scales = "free") + ylim(c(0,NA))


dd <- d[ncores<=16 & !grepl(",",cores)]

ggplot(dd) + geom_boxplot(aes(x = pcores, y = runtime, color = tool)) +
  coord_flip() + facet_wrap(~tool+size, scales = "free") + ylim(c(0,NA))

dd_1c <- dd[ncores==1,.(runtime_1c=mean(runtime)),by=.(tool,size)]
dd <- merge(dd, dd_1c,all.x = TRUE, allow.cartesian = TRUE)

dd[, speedup := (1/runtime)/(1/runtime_1c), by=.(tool,size)]
xtabs(speedup~size+tool, dd[ncores==16, .(speedup=mean(speedup)), by=.(tool, size)])

ggplot(dd) + geom_boxplot(aes(x = as.factor(ncores), y = speedup, color = tool)) +
  facet_grid(tool~size, scales = "free")


ggplot(d) + geom_boxplot(aes(x = as.factor(size), y = auc, color = tool)) 

merge(d[ncores==64], dd_1c,all.x = TRUE, allow.cartesian = TRUE)[,
    mean(runtime/runtime_1c), by=.(tool,size)][order(tool,size)]

```

